name: Check

on:
  push:
    paths:
      - ".github/workflows/check.yml"
      - "packages.install"
      - "packages.uninstall"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    container:
      image: archlinux/archlinux:latest
      options: --privileged
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: /var/cache/pacman/pkg
          key: ${{ runner.os }}

      - run: pacman-key --init
      - run: pacman-key --populate archlinux
      - run: pacman-key --recv-key 3056513887B78AEB
      - run: pacman-key --lsign-key 3056513887B78AEB
      - run: cp -v root/etc/pacman.conf /etc/pacman.conf
      - run: cp -vr root/etc/pacman.d/hooks /etc/pacman.d
      - run: pacman -Sy --noconfirm --needed archlinuxcn-keyring chaotic-keyring
      - run: pacman -Sy --noconfirm --needed $(<packages.install)
      - run: pacman -Sy --noconfirm --needed $(<packages.uninstall)
      - run: pacman -Rsc --noconfirm $(<packages.uninstall)
